### PR TITLE
componentize, readability

### PR DESCRIPTION
**Pull request by PhillipDaum**
Hey Guys,

Have a look at at this. I componentized everything. A little bit of the CSS got changed. I think it will be easier for us to change things, but please let me know what you think before we move on.

Phil

### CODE REVIEW

**Comment by nixx222** [comment]
This looks great! I love the modifications that you made.

Is there something I need to do? I saw something that says it needs
approval?

Thanks for working on this, I studied prompt engineering today and saw
where I can translate the system settings into code. I’m going to play
around with it and do more research on the parameters for Finley.

**Comment by PhillipDaum** [comment]
If two of us approve this, then my new code will get pushed to the main branch, which is the one hosted by Netlify. 

Cat (teacher), is knowledgable about Git, and was helping me set up everything like it ought to be. She can finish showing us when we are back from break.

**Comment by aj1441** [comment]
Ok, I will take a look at this today!

**Review by aj1441 — APPROVED** [review]
This looks good. The additions of the components, routes and pages will make this much easier for us to collaborate and countiue to build this to our end project. Thank you for the work you are doing!

**Review by broscoe — APPROVED** [review]
This looks great! I got some advice on the prompt stuff too, its not fully sorted out but I think it'll be easier to add in once I iron it out a little more and I pull this new version!

**Review by nixx222 — APPROVED** [review]
This is so cool. Thanks Philiam ✌🏻

**Pull request merged**
